import type { LucideIcon } from "lucide-react";
import type { UserRole } from "@/components/auth/auth-context";
import type { AppFeature, AppVertical } from "@/core/tenant/platform-config";
import { hasFeatureEnabled, hasVerticalEnabled } from "@/core/tenant/platform-config";
import {
  Armchair,
  Archive,
  BarChart3,
  BedDouble,
  BookUser,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  ChefHat,
  ClipboardList,
  Coffee,
  ConciergeBell,
  CreditCard,
  DoorOpen,
  FileText,
  Globe,
  KeyRound,
  LayoutDashboard,
  Mail,
  MapPin,
  Maximize,
  Monitor,
  Package,
  Pizza,
  QrCode,
  ScrollText,
  Settings,
  Shield,
  ShoppingBag,
  Soup,
  Star,
  Store,
  Terminal,
  Truck,
  UserCheck,
  Users,
  UtensilsCrossed,
  Wine,
  Wrench,
} from "lucide-react";

export type NavItem = {
  id: string;
  label: string;
  hint: string;
  href: string;
  icon: LucideIcon;
  ready: boolean;
  visibleFor?: UserRole[];
  vertical?: AppVertical;
  feature?: AppFeature;
};

export type NavSection = { title: string; items: NavItem[] };

export const navSections: NavSection[] = [
  {
    title: "Oggi",
    items: [
      {
        id: "dashboard",
        label: "Panoramica",
        hint: "Tutto quello che conta, in un colpo d'occhio.",
        href: "/dashboard",
        icon: LayoutDashboard,
        ready: true,
      },
    ],
  },
  {
    title: "Operatività",
    items: [
      {
        id: "rooms",
        label: "Sala",
        hint: "Planimetria touch, tavoli e azioni.",
        href: "/rooms",
        icon: Armchair,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "sala-fullscreen",
        label: "Sala Fullscreen",
        hint: "Mappa tavoli a schermo intero.",
        href: "/sala-fullscreen",
        icon: Maximize,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "cucina",
        label: "Cucina",
        hint: "KDS comande, ricette, HACCP.",
        href: "/cucina",
        icon: ChefHat,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "pizzeria",
        label: "Pizzeria",
        hint: "KDS pizze, ricette, note.",
        href: "/pizzeria",
        icon: Pizza,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "bar",
        label: "Bar",
        hint: "KDS bevande, cocktail, note.",
        href: "/bar",
        icon: Wine,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "cassa",
        label: "Cassa",
        hint: "POS, conti, pagamenti.",
        href: "/cassa",
        icon: CreditCard,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "chiusura",
        label: "Chiusura Z",
        hint: "Chiusura giornaliera e report.",
        href: "/chiusura",
        icon: ScrollText,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "asporto",
        label: "Asporto",
        hint: "Ordini da asporto e consegne.",
        href: "/asporto",
        icon: ShoppingBag,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "prenotazioni",
        label: "Prenotazioni",
        hint: "Agenda e disponibilità.",
        href: "/prenotazioni",
        icon: ClipboardList,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
    ],
  },
  {
    title: "Hotel",
    items: [
      {
        id: "hotel",
        label: "Hotel Dashboard",
        hint: "Reception, occupazione e stato camere.",
        href: "/hotel",
        icon: BedDouble,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
      },
      {
        id: "hotel-rooms",
        label: "Camere",
        hint: "Stato camere, disponibilità e blocchi.",
        href: "/hotel/rooms",
        icon: MapPin,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
      },
      {
        id: "hotel-planner",
        label: "Planner Camere",
        hint: "Vista mensile PMS per disponibilità e occupazione.",
        href: "/hotel/planner",
        icon: CalendarDays,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
      },
      {
        id: "hotel-reservations",
        label: "Prenotazioni Hotel",
        hint: "Arrivi, partenze e conferme soggiorni.",
        href: "/hotel/reservations",
        icon: CalendarDays,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
      },
      {
        id: "hotel-checkin",
        label: "Check-in / Check-out",
        hint: "Front desk e movimenti ospiti.",
        href: "/hotel/front-desk",
        icon: DoorOpen,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
      },
      {
        id: "hotel-housekeeping",
        label: "Housekeeping",
        hint: "Pulizie, camere pronte e manutenzione.",
        href: "/hotel/housekeeping",
        icon: Shield,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
      },
      {
        id: "hotel-keycards",
        label: "Keycard / Serrature",
        hint: "Accessi camera e stato tessere.",
        href: "/hotel/keycards",
        icon: KeyRound,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
      },
      {
        id: "hotel-folio",
        label: "Guest Folio",
        hint: "Conto unico ospite e movimenti integrati.",
        href: "/hotel/folio",
        icon: CreditCard,
        ready: true,
        vertical: "integration",
        feature: "integration_unified_folio",
      },
      {
        id: "hotel-turni",
        label: "Turni Hotel",
        hint: "Pianificazione turni settimanali e mensili per il personale alberghiero.",
        href: "/hotel/turni",
        icon: CalendarClock,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
        visibleFor: ["hotel_manager", "reception", "housekeeping", "supervisor", "owner", "super_admin"],
      },
      {
        id: "hotel-staff",
        label: "Staff Hotel",
        hint: "Reception, concierge, housekeeping, portiere di notte e tutto il personale.",
        href: "/hotel/staff",
        icon: Users,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
        visibleFor: ["hotel_manager", "supervisor", "owner", "super_admin"],
      },
      {
        id: "hotel-staff-hr",
        label: "HR Hotel",
        hint: "Presenze, ferie, ore e costo personale alberghiero.",
        href: "/hotel/staff-hr",
        icon: UserCheck,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
        visibleFor: ["hotel_manager", "supervisor", "owner", "super_admin"],
      },
      {
        id: "hotel-room-service",
        label: "Room Service",
        hint: "Gestione richieste in camera: food, lavanderia, minibar e servizi extra.",
        href: "/hotel/room-service",
        icon: ConciergeBell,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
        visibleFor: ["reception", "hotel_manager", "supervisor", "owner", "super_admin"],
      },
      {
        id: "hotel-my-tasks",
        label: "I miei incarichi",
        hint: "Richieste assegnate al tuo reparto — portineria, housekeeping, servizi.",
        href: "/hotel/my-tasks",
        icon: CalendarCheck,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
        visibleFor: ["staff", "reception", "housekeeping", "hotel_manager"],
      },
      {
        id: "hotel-qr-rooms",
        label: "QR Camere",
        hint: "Genera e stampa QR code per ogni camera — gli ospiti ordinano room service autonomamente.",
        href: "/hotel/qr-rooms",
        icon: QrCode,
        ready: true,
        vertical: "hotel",
        feature: "hotel",
        visibleFor: ["hotel_manager", "supervisor", "owner", "super_admin"],
      },
    ],
  },
  {
    title: "Gestione",
    items: [
      {
        id: "magazzino",
        label: "Magazzino",
        hint: "Inventario, ricezione, movimenti.",
        href: "/magazzino",
        icon: Package,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "fornitori",
        label: "Fornitori",
        hint: "Anagrafica, ordini, fatture.",
        href: "/fornitori",
        icon: Truck,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "menu-admin",
        label: "Menu Admin",
        hint: "Piatti, prezzi, food cost.",
        href: "/menu-admin",
        icon: Soup,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "daily-menu",
        label: "Menu del Giorno",
        hint: "Piatti del giorno attivi.",
        href: "/daily-menu",
        icon: Star,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "food-cost",
        label: "Food Cost",
        hint: "Calcolo costi e margini.",
        href: "/food-cost",
        icon: FileText,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "catering",
        label: "Catering",
        hint: "Preset, eventi, calcolatore.",
        href: "/catering",
        icon: UtensilsCrossed,
        ready: true,
        vertical: "restaurant",
        feature: "restaurant",
      },
    ],
  },
  {
    title: "Persone",
    items: [
      {
        id: "staff",
        label: "Staff",
        hint: "Dipendenti, turni, presenze.",
        href: "/staff",
        icon: Users,
        ready: true,
      },
      {
        id: "turni",
        label: "Turni",
        hint: "Pianificazione turni settimanali e mensili per area.",
        href: "/turni",
        icon: CalendarClock,
        ready: true,
        visibleFor: ["sala", "cucina", "bar", "pizzeria", "supervisor", "owner", "super_admin"],
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "staff-hr",
        label: "Staff HR",
        hint: "Presenze, ferie, pagamenti, disciplina.",
        href: "/staff-hr",
        icon: UserCheck,
        ready: true,
      },
      {
        id: "staff-me",
        label: "Il Mio Profilo",
        hint: "Turni, ferie, timbrature.",
        href: "/staff-me",
        icon: BookUser,
        ready: true,
      },
      {
        id: "customers",
        label: "CRM Clienti",
        hint: "Anagrafica, preferenze, allergie.",
        href: "/customers",
        icon: Globe,
        ready: true,
      },
      {
        id: "supervisor",
        label: "Supervisor",
        hint: "KPI, report, controllo totale.",
        href: "/supervisor",
        icon: BarChart3,
        ready: true,
      },
    ],
  },
  {
    title: "Archivio",
    items: [
      {
        id: "archivio",
        label: "Archivio",
        hint: "Incassi, fatture, comande, ordini fornitore.",
        href: "/archivio",
        icon: Archive,
        ready: true,
      },
      {
        id: "archivio-comande",
        label: "Archivio Comande",
        hint: "Storico ordini, ricerca, export.",
        href: "/archivio-comande",
        icon: ClipboardList,
        ready: true,
      },
    ],
  },
  {
    title: "Sistema",
    items: [
      {
        id: "hardware",
        label: "Hardware / Stampa",
        hint: "Dispositivi e rotte di stampa (stampanti, display KDS).",
        href: "/hardware",
        icon: Monitor,
        ready: true,
        visibleFor: ["owner", "super_admin"],
      },
      {
        id: "qr-tables",
        label: "QR Tavoli",
        hint: "Genera URL e QR code firmati per ogni tavolo.",
        href: "/qr-tables",
        icon: QrCode,
        ready: true,
        visibleFor: ["owner", "super_admin", "supervisor"],
        vertical: "restaurant",
        feature: "restaurant",
      },
      {
        id: "owner",
        label: "Area Owner",
        hint: "Licenza, SMTP, configurazione.",
        href: "/owner",
        icon: Settings,
        ready: true,
      },
      {
        id: "licenses",
        label: "Licenze",
        hint: "Gestione licenza e abbonamento.",
        href: "/licenses",
        icon: KeyRound,
        ready: true,
        visibleFor: ["super_admin"],
      },
      {
        id: "sessions",
        label: "Sessioni",
        hint: "Le tue sessioni attive — revoca puntuale.",
        href: "/sessions",
        icon: Shield,
        ready: true,
      },
    ],
  },
  {
    title: "Integrazioni",
    items: [
      {
        id: "stripe",
        label: "Stripe",
        hint: "Pagamenti online, abbonamento.",
        href: "/stripe",
        icon: CreditCard,
        ready: true,
        visibleFor: ["super_admin"],
      },
      {
        id: "email-settings",
        label: "Email / SMTP",
        hint: "SMTP per tenant (TenantEmailConfig). Template predefiniti + ultimo test.",
        href: "/email-settings",
        icon: Mail,
        ready: true,
        visibleFor: ["super_admin"],
      },
    ],
  },
  {
    title: "Admin",
    items: [
      {
        id: "super-admin",
        label: "Super Admin",
        hint: "Gestione tenant, licenze, sistema.",
        href: "/super-admin",
        icon: Wrench,
        ready: true,
        visibleFor: ["super_admin"],
      },
      {
        id: "dev-access",
        label: "Dev Access",
        hint: "Bridge emergenza, diagnostica.",
        href: "/dev-access",
        icon: Terminal,
        ready: true,
        visibleFor: ["super_admin"],
      },
    ],
  },
];

export function getVisibleNavSections(userRole?: UserRole | null) {
  const isSuperAdmin = userRole === "super_admin";
  return navSections
    .map((section) => ({
      ...section,
      items: section.items.filter((item) => {
        if (!hasVerticalEnabled(item.vertical)) return false;
        if (!hasFeatureEnabled(item.feature)) return false;
        if (!item.ready && !isSuperAdmin) return false;
        if (!item.visibleFor) return true;
        if (!userRole) return false;
        return item.visibleFor.includes(userRole);
      }),
    }))
    .filter((section) => section.items.length > 0);
}
