import type { LucideIcon } from "lucide-react";
import type { UserRole } from "@/components/auth/auth-context";
import {
  Armchair,
  Archive,
  BarChart3,
  BookUser,
  ChefHat,
  ClipboardList,
  Coffee,
  CreditCard,
  FileText,
  Globe,
  KeyRound,
  LayoutDashboard,
  Mail,
  MapPin,
  Maximize,
  Monitor,
  Package,
  Pizza,
  Plug,
  QrCode,
  ScrollText,
  Settings,
  Shield,
  ShoppingBag,
  Soup,
  Star,
  Store,
  Terminal,
  Truck,
  UserCheck,
  Users,
  UtensilsCrossed,
  Wine,
  Wrench,
} from "lucide-react";

export type NavItem = {
  id: string;
  label: string;
  hint: string;
  href: string;
  icon: LucideIcon;
  ready: boolean;
  visibleFor?: UserRole[];
};

export type NavSection = { title: string; items: NavItem[] };

export const navSections: NavSection[] = [
  {
    title: "Oggi",
    items: [
      {
        id: "dashboard",
        label: "Panoramica",
        hint: "Tutto quello che conta, in un colpo d'occhio.",
        href: "/dashboard",
        icon: LayoutDashboard,
        ready: true,
      },
    ],
  },
  {
    title: "Operatività",
    items: [
      {
        id: "rooms",
        label: "Sala",
        hint: "Planimetria touch, tavoli e azioni.",
        href: "/rooms",
        icon: Armchair,
        ready: true,
      },
      {
        id: "sala-fullscreen",
        label: "Sala Fullscreen",
        hint: "Mappa tavoli a schermo intero.",
        href: "/sala-fullscreen",
        icon: Maximize,
        ready: true,
      },
      {
        id: "cucina",
        label: "Cucina",
        hint: "KDS comande, ricette, HACCP.",
        href: "/cucina",
        icon: ChefHat,
        ready: true,
      },
      {
        id: "pizzeria",
        label: "Pizzeria",
        hint: "KDS pizze, ricette, note.",
        href: "/pizzeria",
        icon: Pizza,
        ready: true,
      },
      {
        id: "bar",
        label: "Bar",
        hint: "KDS bevande, cocktail, note.",
        href: "/bar",
        icon: Wine,
        ready: true,
      },
      {
        id: "cassa",
        label: "Cassa",
        hint: "POS, conti, pagamenti.",
        href: "/cassa",
        icon: CreditCard,
        ready: true,
      },
      {
        id: "chiusura",
        label: "Chiusura Z",
        hint: "Chiusura giornaliera e report.",
        href: "/chiusura",
        icon: ScrollText,
        ready: true,
      },
      {
        id: "asporto",
        label: "Asporto",
        hint: "Ordini da asporto e consegne.",
        href: "/asporto",
        icon: ShoppingBag,
        ready: true,
      },
      {
        id: "prenotazioni",
        label: "Prenotazioni",
        hint: "Agenda e disponibilità.",
        href: "/prenotazioni",
        icon: ClipboardList,
        ready: true,
      },
    ],
  },
  {
    title: "Gestione",
    items: [
      {
        id: "magazzino",
        label: "Magazzino",
        hint: "Inventario, ricezione, movimenti.",
        href: "/magazzino",
        icon: Package,
        ready: true,
      },
      {
        id: "fornitori",
        label: "Fornitori",
        hint: "Anagrafica, ordini, fatture.",
        href: "/fornitori",
        icon: Truck,
        ready: true,
      },
      {
        id: "menu-admin",
        label: "Menu Admin",
        hint: "Piatti, prezzi, food cost.",
        href: "/menu-admin",
        icon: Soup,
        ready: true,
      },
      {
        id: "daily-menu",
        label: "Menu del Giorno",
        hint: "Piatti del giorno attivi.",
        href: "/daily-menu",
        icon: Star,
        ready: true,
      },
      {
        id: "food-cost",
        label: "Food Cost",
        hint: "Calcolo costi e margini.",
        href: "/food-cost",
        icon: FileText,
        ready: true,
      },
      {
        id: "catering",
        label: "Catering",
        hint: "Preset, eventi, calcolatore.",
        href: "/catering",
        icon: UtensilsCrossed,
        ready: true,
      },
    ],
  },
  {
    title: "Persone",
    items: [
      {
        id: "staff",
        label: "Staff",
        hint: "Dipendenti, turni, presenze.",
        href: "/staff",
        icon: Users,
        ready: true,
      },
      {
        id: "staff-hr",
        label: "Staff HR",
        hint: "Presenze, ferie, pagamenti, disciplina.",
        href: "/staff-hr",
        icon: UserCheck,
        ready: true,
      },
      {
        id: "staff-me",
        label: "Il Mio Profilo",
        hint: "Turni, ferie, timbrature.",
        href: "/staff-me",
        icon: BookUser,
        ready: true,
      },
      {
        id: "customers",
        label: "CRM Clienti",
        hint: "Anagrafica, preferenze, allergie.",
        href: "/customers",
        icon: Globe,
        ready: true,
      },
      {
        id: "supervisor",
        label: "Supervisor",
        hint: "KPI, report, controllo totale.",
        href: "/supervisor",
        icon: BarChart3,
        ready: true,
      },
    ],
  },
  {
    title: "Archivio",
    items: [
      {
        id: "archivio",
        label: "Archivio",
        hint: "Incassi, fatture, comande.",
        href: "/archivio",
        icon: Archive,
        ready: true,
      },
      {
        id: "archivio-comande",
        label: "Archivio Comande",
        hint: "Storico ordini, ricerca, export.",
        href: "/archivio-comande",
        icon: ClipboardList,
        ready: true,
      },
    ],
  },
  {
    title: "Sistema",
    items: [
      {
        id: "hardware",
        label: "Hardware / Stampa",
        hint: "Stampanti, rotte, coda.",
        href: "/hardware",
        icon: Monitor,
        ready: true,
      },
      {
        id: "qr-tables",
        label: "QR Tavoli",
        hint: "Codici QR per ogni tavolo.",
        href: "/qr-tables",
        icon: QrCode,
        ready: true,
      },
      {
        id: "owner",
        label: "Area Owner",
        hint: "Licenza, SMTP, configurazione.",
        href: "/owner",
        icon: Settings,
        ready: true,
      },
      {
        id: "licenses",
        label: "Licenze",
        hint: "Gestione licenza e abbonamento.",
        href: "/licenses",
        icon: KeyRound,
        ready: true,
        visibleFor: ["super_admin"],
      },
      {
        id: "sessions",
        label: "Sessioni",
        hint: "Sessioni attive, logout remoto.",
        href: "/sessions",
        icon: Shield,
        ready: true,
      },
    ],
  },
  {
    title: "Integrazioni",
    items: [
      {
        id: "stripe",
        label: "Stripe",
        hint: "Pagamenti online, abbonamento.",
        href: "/stripe",
        icon: CreditCard,
        ready: true,
        visibleFor: ["super_admin"],
      },
      {
        id: "email-settings",
        label: "Email / SMTP",
        hint: "Configurazione email e template.",
        href: "/email-settings",
        icon: Mail,
        ready: true,
      },
      {
        id: "websocket",
        label: "WebSocket",
        hint: "Monitor connessioni real-time.",
        href: "/websocket",
        icon: Plug,
        ready: true,
        visibleFor: ["super_admin"],
      },
    ],
  },
  {
    title: "Admin",
    items: [
      {
        id: "super-admin",
        label: "Super Admin",
        hint: "Gestione tenant, licenze, sistema.",
        href: "/super-admin",
        icon: Wrench,
        ready: true,
        visibleFor: ["super_admin"],
      },
      {
        id: "dev-access",
        label: "Dev Access",
        hint: "Bridge emergenza, diagnostica.",
        href: "/dev-access",
        icon: Terminal,
        ready: true,
        visibleFor: ["super_admin"],
      },
    ],
  },
];
